apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  serviceAccount:
    name: logcollector
  inputs:
    - name: only-xfe-logs
      type: application
      application:
        namespaces:
          - xfe
    - name: appx-logs
      type: application
      application:
        namespaces:
          - appx-production
  outputs:
    - name: rsyslog-east
      type: syslog
      syslog:
        url: tls://74:5044  # Replace 74 with your actual hostname
        rfc: RFC5424
      tls:
        insecureSkipVerify: true
    - name: rsyslog-east-new-elk
      type: syslog
      syslog:
        url: tls://east.lb.appdomain.cloud:5044
        rfc: RFC5424
      tls:
        insecureSkipVerify: true
    - name: appx-london
      type: syslog
      syslog:
        url: tls://171:50455  # Replace 171 with your actual hostname
        rfc: RFC5424
      tls:
        insecureSkipVerify: true
    - name: appx-london-new-elk
      type: syslog
      syslog:
        url: tls://5t.lb.appdomain.cloud:5045
        rfc: RFC5424
      tls:
        insecureSkipVerify: true
  pipelines:
    - name: to-xfe-elk
      inputRefs:
        - only-xfe-logs
      outputRefs:
        - rsyslog-east
        - rsyslog-east-new-elk
      parse: json
    - name: to-appx-elk
      inputRefs:
        - appx-logs
      outputRefs:
        - appx-london
        - appx-london-new-elk
      parse: json
